### ISSUE TITLE
Missed links

### ISSUE THREAD

**Issue by fmarco76** [indigo-dc/fgAPIServer#31]
According to the specification [1] all the resource should have internal links in the header and in the json using the attribute _links.

The links in the header are not present. The attribute _links in the json output are present in the collection but not when a single resource is retrieved.

[1] [http://docs.fgapis.apiary.io/#reference/v1.0](http://docs.fgapis.apiary.io/#reference/v1.0)

**Comment by ricsxn** [comment]
Feature is partially implemented in new_changes

**Comment by ricsxn** [comment]
now completed still in new_changes
