### ISSUE TITLE
Corrupted database when POST-ing application JSON more than once

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgAPIServer#33]
Running `POST` to install a new application more than once, makes it impossible to use it or remove it. The database gets corrupted and you cannot do anything. The `DELETE` method sends message about success but nothing changes. Manual intervention in the database is not possible either because some foreign key restraints are broken.

Tested on fgAPIServer v0.0.6-a.

**Comment by ricsxn** [comment]
Maybe this is already fixed during last developments done together with Marco for his app management portlet.
Could you please send me the the FK error message if you have it? 

Regards,
Riccardo

**Comment by ricsxn** [comment]
Issue not present in latest branch new_changes
