### ISSUE TITLE
Missing "_links" field in task details

### ISSUE THREAD

**Issue by smamczak** [indigo-dc/fgAPIServer#35]
Hi, when I list tasks using
```
GET /v1.0/tasks
```
I get list of tasks. Each tasks has filed named "_links" which I use for file upload. But when I use
```
GET /v1.0/tasks/123
```
I get tasks details without filed named "_links".

Would it be possible to add this filed to task details method?

**Comment by smamczak** [comment]
Could I get an answer to my question?

**Comment by ricsxn** [comment]
available in new_changes branch
