### ISSUE TITLE
Delete the task list returns 405 Method not allowed

### ISSUE THREAD

**Issue by smamczak** [indigo-dc/fgAPIServer#38]
According to the documentation, this method should work http://docs.fgapis.apiary.io/#reference/v1.0/task-collection/delete-the-task-list but I get

```
<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

**Comment by ricsxn** [comment]
delete taks list is currently not implemented
API specs are also missing the BODY usage example
