### ISSUE TITLE
Empty authorization token causes error 500 instead of 401

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgAPIServer#51]
When you contact fgAPIServer with invalid token, you get error `401 Unauthorized` which is expected. However empty authorization token results in `500 Internal Server Error`. Empty here means either 0-length or consisting of all whitespace characters,

To reproduce:
```bash
$ curl -H 'Authorization: Bearer qwerty' https://fgw01.ncg.ingrid.pt/apis/v1.0/applications
# 401 Unauthorized
$ curl -H 'Authorization: Bearer' https://fgw01.ncg.ingrid.pt/apis/v1.0/applications
# 500 Internal Server Error
$ curl -H 'Authorization: Bearer         ' https://fgw01.ncg.ingrid.pt/apis/v1.0/applications
# 500 Internal Server Error
```

Expected outcome: all three above resulting in `401 Unauthorized`

**Comment by ricsxn** [comment]
Solved in new_changes branch
