### ISSUE TITLE
A non-unique column fg_user.name is used in SQL subqueries expecting to return a single, unique value

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgAPIServer#67]
The database table `fg_user` contains column `name` which is not unique. However, business logic in the code assumes this is so, and uses this column in subqueries expecting a single result will be present. 

An example query which fails because of this unmatched expectation is in `ToscaInterfaceDB.getToken()` method of indigo-dc/APIServerDaemon. The issue is submitted for indigo-dc/fgAPIServer, because it controls database schema.

**Comment by ricsxn** [comment]
I believe the query is:

sql = "select tk.token" + LS
                    + "  ,tk.subject" + LS
                    + "from as_queue aq," + LS
                    + "     task t," + LS
                    + "     fg_token tk" + LS
                    + "where aq.task_id=t.id" + LS
                    + "  and tk.user_id = (select id" + LS
                    + "                    from fg_user u" + LS
                    + "                    where u.name=t.user)" + LS
                    + "  and aq.task_id=?" + LS
                    + "order by tk.creation desc limit 1;";

A possible workaround should be to change this in 

sql = "select tk.token" + LS
                    + "  ,tk.subject" + LS
                    + "from as_queue aq," + LS
                    + "     task t," + LS
                    + "     fg_token tk" + LS
                    + "where aq.task_id=t.id" + LS
                    + "  and tk.user_id **in** (select id" + LS
                    + "                    from fg_user u" + LS
                    + "                    where u.name=t.user)" + LS
                    + "  and aq.task_id=?" + LS
                    + "order by tk.creation desc limit 1;";

However it is possible that new official release will include the UNIQUE entry in table creation.
