### ISSUE TITLE
SQL relations do not have ON CASCADE with foreign keys

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgAPIServer#68]
The database schema lacks `ON CASCADE` settings when foreign keys are set up. Therefore, deleting some of the entries is impossible and user needs to do it on a one-by-one basis. 

An example of this is foreign key relation from`fg_user_group.user_id` to `fg_user.id`. FG user cannot be deleted because of this.

**Comment by ricsxn** [comment]
DB Schema 'lacks' this by its design. It is up to the code managing data relationship in the correct way preserving data dependencies.
