### ISSUE TITLE
MySQL-python dependency does not work with latest MariaDB and has not been updated since 2014

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgAPIServer#74]
__NOTE! This issue relates to FutureGatewayFramework/fgAPIServer project which has disabled issue submission.__

`fgAPIServer` uses `MySQL-python` to connect to the database. With the latest MariaDB 10.4.7, it is impossible to install this dependency due to API change:
```
$ pip install MySQL-python
...
    gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/include/mysql -I/usr/include/mysql/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o
    In file included from _mysql.c:44:
    /usr/include/mysql/my_config.h:3:2: warning: #warning This file should not be included by clients, include only <mysql.h> [-Wcpp]
        3 | #warning This file should not be included by clients, include only <mysql.h>
          |  ^~~~~~~
    _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
    _mysql.c:2005:41: error: ‘MYSQL’ {aka ‘struct st_mysql’} has no member named ‘reconnect’
     2005 |  if ( reconnect != -1 ) self->connection.reconnect = reconnect;
          |                                         ^
    error: command 'gcc' failed with exit status 1
```

The problem is that `MySQL-python` is an unofficial client and it has not been in active development for a long time. `fgAPIServer` should use the official MySQL connector or maybe some ORM alternative.

**Comment by ricsxn** [comment]
The supported (best effort basis) release of FG includes this change under the branch 'py2py3'. Since this version, fgAPIServer uses: PyMySQL (https://github.com/PyMySQL/PyMySQL).
https://github.com/FutureGatewayFramework/fgAPIServer/blob/py2py3/requirements.txt
