### ISSUE TITLE
New tasks have creation date literally equal to %Y-%m-%dT-%TZ

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgAPIServer#75]
Steps to reproduce:
- Submit a new task (POST method)
- Retrieve task details (GET method)

In the response body, the `date` field in JSON will be literally equal to `%Y-%m-%dT-%TZ`

UPDATE: I have checked that the database has correct values (e.g. `2019-10-01 07:48:26`). It is the backend that prepares wrong response.

**Comment by ricsxn** [comment]
Unable to reproduce the problem, steps performed:
1) Extraction of the code from this repo:
 ```
git clone https://github.com/indigo-dc/fgAPIServer.giy
```
2) virtualenv activation and Installation of python packages
```
cd fgAPIServer
virtualenv venv
. ./venv/bin/activate
pip install -r requirements.txt
```
3) Extraciton of the FGDB node (v0.1 has a compatible schema version) and its execution:
```
docker pull futuregateway/fgdb:0.1
docker run --name fgdb -p 3306:3306 -d futuregateway/fgdb:0.1
```
4) Config and run fgAPIServer
```
sed -i'fgapiserver.conf_old' s/^fgapisrv_notoken\ .*/fgapisrv_notoken\ =\ True/ fgapiserver.conf
sed -i'fgapiserver.conf_old' s/^fgapisrv_notokenuser\ .*/fgapisrv_notoken\ =\ futuregateway/ fgapiserver.conf
./fgapiserver.py
```
5) Setup the app (sayhello)
```
cd apps
curl -i -H "Content-Type: application/json" -X POST -d '{"application":"2","description":"sayhello@csgfsdk test run", "arguments": ["\"I am saying hello!\""],  "output_files": [{"name":"sayhello.data"}], "input_files": [{"name":"sayhello.sh"},{"name":"sayhello.txt"}]}' http://localhost:8888/v1.0/tasks
```
6) Get task detail:
```
curl http://localhost:8888/v1.0/tasks/1
{
    "status": "WAITING", 
    "description": "sayhello@csgfsdk test run", 
    "creation": "2019-10-01T11:15:29Z", 
    "iosandbox": "/tmp/c6b1e391-e43c-11e9-8f6e-c82a145797b3", 
    "user": "futuregateway", 
    "id": "1", 
    "output_files": [
        {
            "url": "", 
            "name": "sayhello.data"
        }, 
        {
            "url": "", 
            "name": "sayhello.out"
        }, 
        {
            "url": "", 
            "name": "sayhello.err"
        }
    ], 
    "application": "2", 
    "_links": [
        {
            "href": "/v1.0/tasks/1/input", 
            "rel": "input"
        }
    ], 
    "arguments": [
        "\"I am saying hello!\""
    ], 
    "runtime_data": [], 
    "input_files": [
        {
            "status": "NEEDED", 
            "name": "sayhello.sh"
        }, 
        {
            "status": "NEEDED", 
            "name": "sayhello.txt"
        }
    ], 
    "last_change": "2019-10-01T11:15:29Z"
```

The field ```"creation": "2019-10-01T11:15:29Z", ```is correctly reported.

**Comment by tzok** [comment]
I am sorry, I did not specify all the details.

This issue concerns [FutureGatewayFramework/fgAPIServer](https://github.com/FutureGatewayFramework/fgAPIServer) which has disabled issue creation and so I had to report it here. Please enable issue creation for that project, and please retry with that one.


I think the issue is because `mysql.connector` already does some Python object manipulation in the background. When you `SELECT` a column which represents a date and time, it is internally cast into `datetime.datetime` object.
